Repository vodemn/m3_lightmeter, pull requests merged in 2023-07, with the labels that each got.

#86 ML-11 Implement volume buttons actions
  README.md
  android/app/src/main/kotlin/com/vodemn/lightmeter/MainActivity.kt
  lib/data/light_sensor_service.dart
  lib/data/models/volume_action.dart
  lib/data/shared_prefs_service.dart
  lib/data/volume_events_service.dart
  lib/interactors/metering_interactor.dart
  lib/interactors/settings_interactor.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  lib/l10n/intl_ru.arb
  lib/main_prod.dart
  lib/providers.dart
  lib/screens/metering/bloc_metering.dart
  lib/screens/metering/communication/bloc_communication_metering.dart
  lib/screens/metering/communication/event_communication_metering.dart
  lib/screens/metering/communication/state_communication_metering.dart
  lib/screens/metering/components/camera_container/bloc_container_camera.dart
  lib/screens/metering/components/light_sensor_container/bloc_container_light_sensor.dart
  lib/screens/metering/components/light_sensor_container/event_container_light_sensor.dart
  lib/screens/metering/components/shared/volume_keys_notifier/notifier_volume_keys.dart
  lib/screens/metering/event_metering.dart
  lib/screens/metering/flow_metering.dart
  lib/screens/metering/screen_metering.dart
  lib/screens/settings/components/general/components/caffeine/widget_list_tile_caffeine.dart
  lib/screens/settings/components/general/components/haptics/widget_list_tile_haptics.dart
  lib/screens/settings/components/general/components/volume_actions/bloc_list_tile_volume_actions.dart
  lib/screens/settings/components/general/components/volume_actions/provider_list_tile_volume_actions.dart
  lib/screens/settings/components/general/components/volume_actions/widget_list_tile_volume_actions.dart
  lib/screens/settings/components/general/widget_settings_section_general.dart
  lib/screens/settings/components/theme/components/dynamic_color/widget_list_tile_dynamic_color.dart
  lib/screens/settings/flow_settings.dart
  lib/screens/settings/screen_settings.dart
  pubspec.yaml
  resources/social_preview.png
  test/data/light_sensor_service_test.dart
  test/data/volume_events_service_test.dart
  test/screens/metering/bloc_metering_test.dart
  test/screens/metering/communication/bloc_communication_metering_test.dart
  test/screens/metering/components/camera/bloc_container_camera_test.dart
  test/screens/metering/components/light_sensor/bloc_container_light_sensor_test.dart
Labels: feature

#87 ML-62 Interactors tests
  analysis_options.yaml
  lib/interactors/metering_interactor.dart
  lib/interactors/settings_interactor.dart
  lib/screens/metering/components/camera_container/bloc_container_camera.dart
  lib/screens/metering/flow_metering.dart
  test/interactors/metering_interactor_test.dart
  test/interactors/settings_interactor_test.dart
  test/screens/metering/components/camera/bloc_container_camera_test.dart
Labels: improvement

#91 Add Chinese language support
  lib/data/models/supported_locale.dart
  lib/l10n/intl_zh.arb
Labels: improvement

#93 Fixed Chinese translation
  lib/l10n/intl_zh.arb
Labels: bug

#94 Updated README Build section
  .github/workflows/cd_dev.yml
  .github/workflows/cd_prod.yml
  .github/workflows/ci.yml
  README.md
  lib/firebase_options.dart
  lib/main_prod.dart
Labels: documentation, improvement
