Repository vodemn/m3_lightmeter, pull requests merged in 2023-09, with the labels that each got.

#112 Equipment profiles issues
  lib/screens/settings/components/metering/components/equipment_profiles/components/equipment_profile_screen/components/equipment_profile_container/components/equipment_list_tiles/components/dialog_range_picker/widget_dialog_picker_range.dart
  lib/screens/settings/components/metering/components/equipment_profiles/components/equipment_profile_screen/components/equipment_profile_container/widget_container_equipment_profile.dart
  lib/screens/settings/components/metering/components/equipment_profiles/components/equipment_profile_screen/screen_equipment_profile.dart
Labels: bug

#115 Equipment profiles issues
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  lib/l10n/intl_ru.arb
  lib/l10n/intl_zh.arb
  lib/screens/metering/screen_metering.dart
  lib/screens/settings/components/metering/components/metering_screen_layout/components/meterins_screen_layout_features_dialog/widget_dialog_metering_screen_layout_features.dart
Labels: bug

#116 ML-114 Metering container issues
  lib/screens/metering/components/shared/metering_top_bar/shape_top_bar_metering.dart
  lib/screens/metering/components/shared/metering_top_bar/widget_top_bar_metering.dart
  lib/screens/metering/components/shared/readings_container/components/animated_dialog_picker/components/animated_dialog/widget_dialog_animated.dart
Labels: bug

#119 ML-117 Improve description of paid features
  iap/README.md
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  lib/l10n/intl_ru.arb
  lib/l10n/intl_zh.arb
  lib/screens/settings/components/lightmeter_pro/components/buy_pro/widget_list_tile_buy_pro.dart
  lib/screens/settings/components/lightmeter_pro/widget_settings_section_lightmeter_pro.dart
  lib/screens/settings/components/shared/iap_list_tile/widget_list_tile_iap.dart
  lib/screens/settings/components/shared/settings_section/widget_settings_section.dart
  lib/screens/settings/components/utils/show_buy_pro_dialog.dart
  lib/screens/settings/screen_settings.dart
Labels: improvement

#120 ML-113 Add ability to copy equipment profile
  iap/lib/src/providers/equipment_profile_provider.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  lib/l10n/intl_ru.arb
  lib/l10n/intl_zh.arb
  lib/screens/metering/components/bottom_controls/widget_bottom_controls.dart
  lib/screens/metering/components/camera_container/components/camera_controls/components/exposure_offset_slider/widget_slider_exposure_offset.dart
  lib/screens/settings/components/equipment/components/equipment_profiles/components/equipment_profile_screen/components/equipment_profile_container/components/equipment_list_tiles/widget_list_tiles_equipments.dart
  lib/screens/settings/components/equipment/components/equipment_profiles/components/equipment_profile_screen/components/equipment_profile_container/widget_container_equipment_profile.dart
  lib/screens/settings/components/equipment/components/equipment_profiles/components/equipment_profile_screen/screen_equipment_profile.dart
  lib/screens/settings/components/metering/components/calibration/components/calibration_dialog/widget_dialog_calibration.dart
  lib/screens/settings/components/shared/dialog_filter/widget_dialog_filter.dart
  lib/screens/settings/screen_settings.dart
  lib/screens/shared/sliver_screen/screen_sliver.dart
Labels: feature

#122 Fixed PR check
  .github/scripts/stub_iap.sh
  .github/workflows/pr_check.yml
Labels: bug

#125 Update intl_zh.arb of new features
  lib/l10n/intl_zh.arb
Labels: improvement

#127 ML-126 Automate screenshots creation
  .gitignore
  assets/camera_stub_image.jpg
  iap/lib/src/data/models/iap_product.dart
  iap/lib/src/providers/iap_products_provider.dart
  integration_test/generate_screenshots.dart
  integration_test/generate_screenshots.sh
  lib/application.dart
  lib/application_wrapper.dart
  lib/main_dev.dart
  lib/main_prod.dart
  lib/main_release.dart
  lib/platform_config.dart
  lib/screens/metering/components/camera_container/bloc_container_camera.dart
  lib/screens/metering/components/camera_container/components/camera_preview/widget_camera_preview.dart
  lib/screens/settings/components/shared/dialog_filter/widget_dialog_filter.dart
  pubspec.yaml
  test_driver/screenshot_driver.dart
Labels: feature

#128 ML-126 Automate screenshots creation
  integration_test/generate_screenshots.dart
Labels: feature, improvement
