Repository vodemn/m3_lightmeter, pull requests merged in 2024-01, with the labels that each got.

#147 Hide Pro features from the metering screen
  .vscode/launch.json
  lib/application.dart
  lib/l10n/intl_en.arb
  lib/l10n/intl_fr.arb
  lib/l10n/intl_ru.arb
  lib/l10n/intl_zh.arb
  lib/platform_config.dart
  lib/screens/metering/components/camera_container/bloc_container_camera.dart
  lib/screens/metering/components/camera_container/mock_bloc_container_camera.dart
  lib/screens/metering/components/camera_container/provider_container_camera.dart
  lib/screens/metering/components/camera_container/widget_container_camera.dart
  lib/screens/metering/components/shared/readings_container/components/lightmeter_pro/widget_lightmeter_pro.dart
  lib/screens/metering/components/shared/readings_container/components/shared/animated_dialog_picker/components/animated_dialog/widget_dialog_animated.dart
  lib/screens/metering/components/shared/readings_container/components/shared/animated_dialog_picker/components/dialog_picker/widget_picker_dialog.dart
  lib/screens/metering/components/shared/readings_container/components/shared/animated_dialog_picker/widget_picker_dialog_animated.dart
  lib/screens/metering/components/shared/readings_container/components/shared/reading_value_container/widget_container_reading_value.dart
  lib/screens/metering/components/shared/readings_container/widget_container_readings.dart
  lib/screens/settings/components/lightmeter_pro/components/buy_pro/widget_list_tile_buy_pro.dart
  lib/screens/settings/components/lightmeter_pro/widget_settings_section_lightmeter_pro.dart
  lib/screens/settings/components/metering/components/metering_screen_layout/widget_list_tile_metering_screen_layout.dart
  lib/screens/settings/components/shared/dialog_switch/widget_dialog_switch.dart
  lib/screens/settings/components/shared/disable/widget_disable.dart
  lib/screens/settings/components/shared/iap_list_tile/widget_list_tile_iap.dart
  lib/screens/settings/components/theme/components/primary_color/widget_list_tile_primary_color.dart
  lib/screens/settings/utils/show_buy_pro_dialog.dart
  lib/screens/shared/pro_features_dialog/widget_dialog_pro_features.dart
  lib/screens/shared/transparent_dialog/widget_dialog_transparent.dart
  lib/utils/context_utils.dart
  lib/utils/ev_from_bytes.dart
  lib/utils/text_height.dart
  test/application_mock.dart
  test/screens/settings/components/widget_settings_section_lightmeter_pro_test.dart
  test/screens/settings/utils/show_buy_pro_dialog_test.dart
  test/utils/ev_from_bytes_test.dart
Labels: feature

#149 ML-130 Added ff for the "Pro features" tile on the main screen
  lib/data/models/feature.dart
  lib/data/remote_config_service.dart
  lib/screens/metering/components/camera_container/widget_container_camera.dart
  lib/screens/metering/components/shared/readings_container/widget_container_readings.dart
  test/providers/remote_config_provider_test.dart
Labels: dev-only

#150 ML-134 Firebase Remote Config issues
  lib/data/remote_config_service.dart
Labels: bug, Crashlytics

#151 Fix Chinese Translation Errors
  lib/l10n/intl_zh.arb
Labels: bug

#153 ML-152 Added data extraction rules
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/xml/data_extraction_rules.xml
Labels: bug, Crashlytics, platform-android

#155 ML-154 Improve Crashlytics reports
  .vscode/launch.json
  lib/application_wrapper.dart
  lib/data/analytics/analytics.dart
  lib/data/analytics/api/analytics_api_interface.dart
  lib/data/analytics/api/analytics_firebase.dart
  lib/data/analytics/entity/analytics_event.dart
  lib/data/remote_config_service.dart
  lib/firebase.dart
  lib/main_dev.dart
  lib/main_prod.dart
  lib/main_release.dart
  lib/providers/services_provider.dart
  lib/runner.dart
  lib/screens/metering/components/camera_container/bloc_container_camera.dart
  lib/screens/metering/components/camera_container/mock_bloc_container_camera.dart
  lib/screens/metering/components/camera_container/provider_container_camera.dart
  lib/screens/shared/pro_features_dialog/widget_dialog_pro_features.dart
  lib/utils/ev_from_bytes.dart
  pubspec.yaml
  test/screens/metering/components/camera/bloc_container_camera_test.dart
  test/utils/ev_from_bytes_test.dart
Labels: feature, Crashlytics
